"""Knowledge builder for converting blocks to node trees."""

import re
from typing import Optional, List, Dict, Tuple, Set
from kerag.builder.tokenizer import Tokenizer
from kerag.builder.parser import Parser
from kerag.core.id_manager import IDManager
from typing import Any


class KnowledgeBuilderError(Exception):
    """Base exception for knowledge builder errors."""
    pass


class HeaderLevelError(KnowledgeBuilderError):
    """Raised when header level is invalid."""
    pass


class StackEmptyError(KnowledgeBuilderError):
    """Raised when section stack is empty but content expected."""
    pass


class KnowledgeBuilder:
    """Build knowledge node trees from markdown files.

    The KnowledgeBuilder processes blocks generated by the parser and constructs
    a hierarchical tree of nodes representing the document structure.
    """

    def __init__(self, km: Any = None, id_manager: Optional[IDManager] = None, root_path: Optional[str] = None):
        """Initialize the knowledge builder.

        Args:
            km: KnowledgeManager instance.
            id_manager: Namespace manager to use for label resolution.
                             If None, creates a new one.
            root_path: Root path of the knowledge base. If provided, will be set
                      in the id_manager.
        """
        self.km = km
        self.module_building: Optional[str] = None
        self.section_stack: List[Tuple[int, str]] = []  # Store (literal_level, node_id) tuples
        # self.subtree_references: Dict[str, str] = {}  # parent_id -> child_id
        self.file_to_parse: List[str] = []
        self.built_files: Set[str] = set()  # Track all file_ids that have been built
        self.id_manager = id_manager or IDManager()
        if root_path:
            self.id_manager.set_root_path(root_path, None)  # Only set local root
        self._warnings: List[str] = []
        self._file_id: Optional[str] = None
        self._node_counter: int = 0
        self._root_path: Optional[str] = root_path

    def build_file(self, file_path: str):
        """Build nodes from a file.

        Args:
            file_path: Path to the file

        Raises:
            ValueError: If root_path was not set in constructor
        """
        # Reset for new file
        self.built_files.clear()  # Clear built files tracking
        self._warnings = []

        # Set root path in id_manager from this instance's root_path
        if not self._root_path:
            raise ValueError("root_path must be set in KnowledgeBuilder constructor to use build_file()")

        if not self.id_manager._local_root:
            self.id_manager.set_root_path(self._root_path, None)

        # Determine file_id
        self._file_id = self.id_manager.path_to_file_id(file_path)

        # Build the file
        self._build_file(file_path)
        self._finish_all_sections()

    def build_module(self, module_name: str, base_path: Optional[str] = None):
        """Build all nodes for a module.

        Args:
            module_name: Module name (e.g., 'kerag/core')
            base_path: Base directory path to look for files (defaults to this class's root_path)

        Raises:
            KnowledgeBuilderError: If no index file found or other errors
            ValueError: If root_path was not set in constructor
        """
        self.module_building = module_name
        self.built_files.clear()  # Clear built files tracking
        self._warnings = []

        # Use this class's root_path if base_path not provided
        if not base_path:
            if not self._root_path:
                raise ValueError("root_path must be set in KnowledgeBuilder constructor to use build_module()")
            base_path = self._root_path

        # Only set root path in id_manager if no roots are configured
        # This preserves dual-root configuration from KnowledgeManager
        if not self.id_manager._local_root and not self.id_manager._global_root:
            self.id_manager.set_root_path(base_path, None)
            # print(f"[DEBUG] build_module: Set single root path to {base_path}")  # DEBUG
        # else:
            # print(f"[DEBUG] build_module: Using existing dual roots - local: {self.id_manager._local_root}, global: {self.id_manager._global_root}")  # DEBUG

        # Find index file for the module using IDManager
        file_id = module_name
        # print(f"[DEBUG] build_module: Looking for index file with file_id='{file_id}'")  # DEBUG
        index_file = self.id_manager.file_id_to_path(file_id)

        if not index_file:
            raise KnowledgeBuilderError(f"Index file not found for module: {module_name}")

        # Add index file to parse queue
        self.file_to_parse = [str(index_file)]

        # Scan for other files in the module directory
        module_files = self.id_manager.get_files_in_directory(file_id)
        for file_id_in_module in module_files:
            # Skip the index file (already added)
            if file_id_in_module != file_id:
                file_path = self.id_manager.file_id_to_path(file_id_in_module)
                if file_path and str(file_path) not in self.file_to_parse:
                    self.file_to_parse.append(str(file_path))

        # Process all files in queue
        while self.file_to_parse:
            file_path = self.file_to_parse.pop(0)
            # Set file_id for the current file
            self._file_id = self.id_manager.path_to_file_id(file_path)
            try:
                self._build_file(file_path)
            except Exception as e:
                raise KnowledgeBuilderError(f"Error building file {file_path}: {e}")

        # Finish any remaining sections
        self._finish_all_sections()

    def get_warnings(self) -> List[str]:
        """Get all warnings from the last build.

        Returns:
            List of warning messages
        """
        return self._warnings.copy()

    def clear_warnings(self):
        """Clear all warnings."""
        self._warnings = []

    def get_built_files(self) -> Set[str]:
        """Get all file IDs that have been built.

        Returns:
            Set of file IDs that were built during the last build operation
        """
        return self.built_files.copy()

    def clear_built_files(self):
        """Clear the built files tracking set."""
        self.built_files.clear()


    def _build_file(self, file_path: str):
        """Build nodes from a file (internal method).

        Args:
            file_path: Path to the file
        """
        # print(f'[DEBUG] _Build file {file_path}')
        # print(f'[DEBUG] Built files: {self.built_files}')
        
        if file_path in self.built_files:
            # print(f'[DEBUG] _Build file returned')
            return 
        self._node_counter = 0  # Global counter for all nodes in this file
    

        # Determine module path from file path
        module_path = self.id_manager.path_to_module(file_path)

        # Tokenize and parse the file
        tokenizer = Tokenizer()
        parser = Parser()

        tokens = tokenizer.tokenize_file(file_path)
        blocks = parser.parse_tokens(tokens)

        # Process each block
        for block in blocks:
            if block.type.value == "header":
                self._process_header(block, file_path, module_path)
            elif block.type.value == "content":
                self._process_content(block, file_path, module_path)
            elif block.type.value == "subtree_ref":
                self._process_subtree_ref(block, file_path, module_path)
            elif block.type.value == "see_also":
                self._process_see_also(block, file_path, module_path)
            elif block.type.value == "section_fence":
                self._process_section_fence(block)
        # Track that this file has been built
        self.built_files.add(file_path)
        
    def _process_header(self, block, file_path: str, module_path: str):
        """Process a header block.

        Args:
            block: Header block
            file_path: Source file path
            module_path: Module path
        """
        # Get info from block metadata (processed by parser)
        block_info = block.metadata['info']
        literal_level = block_info.level
        label = block_info.label
        line_num = block_info.start_line

        # Title is still in token metadata
        token = block.tokens[0]
        title = token.metadata['title']

        # Generate node ID
        if label:
            node_id = self.id_manager.generate_node_id(
                label=label,
                file_id=self._file_id
            )
        else:
            # Use file_id::__node_N format
            node_id = self.id_manager.generate_node_id(
                file_id=self._file_id,
                file_node_count=self._node_counter
            )
        # Increment global counter for all nodes
        self._node_counter += 1

        # Add node to KB immediately upon detection
        if self.km:
            self.km.kb.add_node(
                node_id=node_id,
                node_type="section",
                file_id=self._file_id,
                module=module_path,
                original_file_path=file_path,
                line_number=line_num,
                label=label or node_id.split("::")[-1]
            )
            # Update section-specific info
            self.km.kb.update_section_info(node_id, title, literal_level)

        # Handle based on stack state
        if not self.section_stack:
            # First section in file - must be level 1
            if literal_level != 1:
                raise HeaderLevelError(
                    f"First header in file must be level 1, got level {literal_level}"
                )
            if self.km:
                self.km.kb.set_child("::ROOT", node_id)
            self.section_stack.append((literal_level, node_id))
        else:
            # Find proper parent (must have level < current level)
            while (self.section_stack and
                   self.section_stack[-1][0] >= literal_level):
                self.section_stack.pop()

            if not self.section_stack:
                # If we popped everything, this is a top-level section
                if literal_level != 1:
                    raise HeaderLevelError(
                        f"Cannot have a level {literal_level} header without parent sections"
                    )
                if self.km:
                    self.km.kb.set_child("::ROOT", node_id)
            else:
                # Found parent
                _, parent_id = self.section_stack[-1]
                if self.km:
                    self.km.kb.set_child(parent_id, node_id)

            # Push current section to stack
            self.section_stack.append((literal_level, node_id))

    def _process_content(self, block, file_path: str, module_path: str):
        """Process a content block.

        Args:
            block: Content block
            file_path: Source file path
            module_path: Module path
        """
        if not self.section_stack:
            raise StackEmptyError("Content block found outside any section")

        # Get block info from metadata
        block_info = block.metadata['info']
        line_num = block_info.start_line
        label = block_info.label

        # Combine all content tokens and handle content_label if present
        content_lines = []
        inline_refs = []  # Collect inline links from all tokens

        for token in block.tokens:
            if token.type == 'content':
                line_content = token.content

                # If this is the last line AND we have a content_label in block info,
                # remove the [@label] part from content
                if (token == block.tokens[-1] and label and
                    token.metadata.get('content_label') == label):
                    # Remove the label from the line
                    line_content = re.sub(r'\s*\[@' + re.escape(label) + r'\]$', '', line_content).rstrip()

                content_lines.append(line_content)

                # Get inline links from token metadata (processed by tokenizer)
                token_links = token.metadata.get('inline_links', [])
                inline_refs.extend(token_links)

        # Join content (handle blank line separation)
        content = '\n'.join(content_lines)

        # Generate node ID
        if label:
            node_id = self.id_manager.generate_node_id(
                label=label,
                file_id=self._file_id
            )
        else:
            # Use file_id::__node_N format
            node_id = self.id_manager.generate_node_id(
                file_id=self._file_id,
                file_node_count=self._node_counter
            )
        # Increment global counter for all nodes
        self._node_counter += 1

        # Add node to KB immediately
        if self.km:
            self.km.kb.add_node(
                node_id=node_id,
                node_type="content",
                file_id=self._file_id,
                module=module_path,
                original_file_path=file_path,
                line_number=line_num,
                label=label or node_id.split("::")[-1]
            )

        # Create content node and resolve inline links
        _, parent_id = self.section_stack[-1]

        # Resolve inline links to node IDs (no validation during build)
        resolved_links = []
        current_file_id = self.id_manager.path_to_file_id(file_path)
        for ref in inline_refs:
            # Expand ref to full node_id format
            ref_node_id = self.id_manager.expand_node_id(ref, current_file_id)
            resolved_links.append(ref_node_id)

        # Update node with content and links via KB API
        if self.km:
            self.km.kb.update_content_info(node_id, content, resolved_links)
            # Parent is current stack top
            if self.section_stack:
                _, parent_id = self.section_stack[-1]
                self.km.kb.set_child(parent_id, node_id)
            else:
                raise StackEmptyError("Content block found outside any section")

    def _process_subtree_ref(self, block, file_path: str, _module_path: str):
        """Process a subtree reference block.

        Args:
            block: Subtree reference block
            file_path: Source file path
            _module_path: Module path (unused)
        """
        if not self.section_stack:
            raise StackEmptyError("Subtree reference found outside any section")

        token = block.tokens[0]
        reference_id = token.metadata.get('reference_id')
        line_num = token.line_number
        literal_level = block.metadata['info'].level
        if not reference_id:
            self._warnings.append(f"Subtree reference without ID at line {line_num}")
            return

        # Find proper parent (must have level < current level)
        while (self.section_stack and
                self.section_stack[-1][0] >= literal_level):
            self.section_stack.pop()

        if not self.section_stack:
            raise StackEmptyError("Subtree reference found outside any section after stack adjustment")

        # Resolve reference ID to file path
        # reference_id may contain path symbols (.., ., %, /)
        current_file_id = self.id_manager.path_to_file_id(file_path)
        ref_node_id = self.id_manager.expand_node_id(reference_id, current_file_id)

        # Convert file_id back to path
        ref_file_path = self.id_manager.file_id_to_path(ref_node_id.split('::')[0])

        # Update to parent's children
        _, parent_id = self.section_stack[-1]

        if self.km:
            self.km.kb.set_child(parent_id, ref_node_id)

        # Store subtree reference
        # self.subtree_references[parent_id] = ref_node_id
        # Queue the file for parsing if not already queued
        if ref_file_path and ref_file_path not in self.file_to_parse:
            self.file_to_parse.append(str(ref_file_path))

    def _process_see_also(self, block, file_path: str, _module_path: str):
        """Process a see-also block.

        Args:
            block: See-also block
            file_path: Source file path
            _module_path: Module path (unused)
        """
        if not self.section_stack:
            raise StackEmptyError("See-also block found outside any section")

        # Get the current section
        literal_level = block.metadata['info'].level
        while (self.section_stack and
                self.section_stack[-1][0] >= literal_level):
            self.section_stack.pop()

        if not self.section_stack:
             raise StackEmptyError("See-also block found outside any section after stack adjustment")

        _, current_section_id = self.section_stack[-1]

        # Get current file_id for relative resolution
        current_file_id = self.id_manager.path_to_file_id(file_path)

        # Process each token in the see-also block
        for token in block.tokens:
            if token.type == 'see_also_header':
                # Header token, skip
                continue
            elif token.type == 'see_also_item':
                # Get reference ID and description from token metadata
                ref_id = token.metadata.get('reference_id')
                description = token.metadata.get('description', '')

                if not ref_id:
                    self._warnings.append(f"See-also item without reference ID at line {token.line_number}")
                    continue

                # Try to resolve the reference
                # Expand to full node_id format (no validation during build)
                # print(f'[DEBUG] Expand see also: {ref_id} in {current_file_id}')
                node_id = self.id_manager.expand_node_id(ref_id, current_file_id)
                # print(f'[DEBUG] Resolved to: {node_id}')

                if self.km:
                    self.km.kb.add_see_also(current_section_id, node_id, description)

            elif token.type == 'blank':
                # Blank line, skip
                continue
            else:
                # Unexpected token type in see-also block
                self._warnings.append(f"Unexpected token type '{token.type}' in see-also block at line {token.line_number}")

    def _process_section_fence(self, _block):
        """Process a section fence block.

        Args:
            _block: Section fence block (unused)
        """
        if self.section_stack:
            # Pop the current section (finish it)
            self.section_stack.pop()
        else:
            self._warnings.append("Section fence found with no open section")
        if self.section_stack:
            # Pop the current section (finish it)
            self.section_stack.pop()
        else:
            self._warnings.append("Section fence found with no open section")

    def _finish_all_sections(self):
        """Finish all remaining sections in the stack."""
        while self.section_stack:
            self.section_stack.pop()

    def _extract_inline_references(self, text: str) -> List[str]:
        """Extract all inline references from text.

        Args:
            text: Text to extract references from

        Returns:
            List of reference IDs
        """
        pattern = re.compile(r'\(@([^)]+)\)')
        return [match.group(1) for match in pattern.finditer(text)]

